#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Author: Chunyu Xue

from typing import Dict, List, Any
from abc import ABC, abstractmethod

import torch
from torch import nn

__all__ = [
    "SubModuleBase",
    "WrappedTensor",
]


class SubModuleBase(ABC):
    """ Base class for sub-module. 
    
    Args:
        input_keywords (List[str]): Keywords required in this sub-module.
        output_keywords (List[str]): Keywords generated by this sub-module.
    """

    def __init__(self, input_keywords: List[str], output_keywords: List[str]):
        super().__init__()
        self.input_keywords = input_keywords
        self.output_keywords = output_keywords
    
    def preprocess(self, intermediate_: Dict[str, Any]):
        inputs = []
        for kw in self.input_keywords:
            inputs.append(intermediate_.pop(kw))
        return inputs

    @abstractmethod
    def forward(self, intermediate_: Dict[str, Any]):
        """ Forward the sub-module with any user-defined codes.
        Any child class must adhere to the input argument format.
        
        Args:
            intermediate_(Dict[str, Any]): Intermediate object that includes all required 
                input keyword arguments, and those required by the latter sub-modules.
        """
        pass

    def postprocess(self, intermediate_: Dict[str, Any], outputs: List[Any]):
        """ Postprocess. 
        
        Args:
            outputs(List[Any]): Outputs of this sub-module in order of output keywords.
        """
        for i, kw in enumerate(self.output_keywords):
            intermediate_[kw] = outputs[i]
        return intermediate_

    def __call__(self, *args, **kwargs):
        return self.forward(*args, **kwargs)


class WrappedTensor:
    """
    A wrapper for tensors that enables caller functions to pass an indirect reference
    to callee functions. By wrapping the tensor, the caller's direct reference is removed,
    allowing the tensor to be garbage collected once the callee unwraps and frees it.
    """

    def __init__(self, tensor: torch.Tensor):
        self._wrapper = [tensor]

    def unwrap(self):
        """
        Returns the wrapped tensor while deleting the internal reference.
        Can only be called once.
        """
        if len(self._wrapper) == 0:
            raise RuntimeError(f"WrappedTensor has already been unwrapped")
        return self._wrapper.pop(0)
